### PR TITLE
Add a "new" pid vid (VID_2A03%PID_0036), for my Leonardo bootloader

### PR DESCRIPTION
**Pull request by AqeeAqee**
Hi Eried!
  Thanks for your great work, your ArduboyUploader is a wonderful tool, so clear, convenient and ful-functional.
  But when I trying it, it doesn't work for me. I found after reset the board it try to get serial port again, but it got the board working port, instead of bootloader port. I found your supposing vid-pid not include what my bootloader serial, so I added it into the "select", and it worked.
  I am a beginner of arduino and arduboy, so I am not sure it is reasonable.
  Just create a pull request, and depending on your decision. Hope it's useful for you and others.

### CODE REVIEW

**Comment by eried** [comment]
Hahaha so many changes, do you have a plugin in VS? I am going to close the PR and add those changes manually.

**Comment by AqeeAqee** [comment]
Sorry! 
But I swear, VS is clean no any plug-in. Maybe the reason is it formated when I pasting codes. In fact, I downloaded your source code, edit in VS and try to debug, After I successed, I forked your project, open it in VS, and paste my working code into it.
I am glad to refork again and make a clean version today later(I am not good at github also, I don't know how to retract commits.)
But I can't testing it any more, after I success, I tried many arduboy games happily. And suddenly, my PC can't show leonardo serial port. I guess the game overwrited bootloarder, then I learned and tried to burn bootloader but it doesn't work yet. :(

**Comment by AqeeAqee** [comment]
I fixed my bootloarder.
And will cook a clean PR later tonight (China).

**Comment by eried** [comment]
Awesome! Thanks!

**Comment by AqeeAqee** [comment]
Done. Created a new PR, https://github.com/eried/ArduboyUploader/pull/3, clearly
:-) 
Welcome, what I did is just a little peice than your great work, and also, I can learning how to use Github at meanwhile.

**Pull request closed without merging**
